#Build image
FROM ubuntu:18.04 as build-step

RUN apt-get -y update
RUN apt-get -y install curl autoconf automake cmake libbz2-dev libace-dev libssl-dev libmysqlclient-dev libtool build-essential

COPY . /mangoserver
RUN mkdir /mangoserver/build
WORKDIR /mangoserver/build

#Install mangos
RUN cmake .. -DCMAKE_INSTALL_PREFIX=/mangos -DCONF_INSTALL_DIR=/mangos/conf -DBUILD_MANGOSD=1 -DBUILD_REALMD=0 -DBUILD_TOOLS=0
RUN make -j4
RUN make install

#data image
FROM ubuntu:18.04 as data-step
RUN mkdir data
WORKDIR /data
ADD https://km-branch.s3-us-west-2.amazonaws.com/1.12.1-extracted-client-data.tar.gz ./data.tar.gz
RUN tar -xvf data.tar.gz &>/dev/null

#Runtime image
FROM ubuntu:18.04 as runtime

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install libmysqlclient20 openssl

COPY --from=build-step /mangos /mangos
WORKDIR /mangos/bin
RUN chmod +x mangosd
WORKDIR /mangos/conf
RUN for f in *.dist; do cp "$f" "${f%%.conf.dist}.conf"; done

COPY --from=data-step /data /mangos/data

EXPOSE 8085
ENTRYPOINT [ "/mangos/bin/mangosd" ]
