name: Mangos amd64 Image Pipeline

on:
  push:
    branches: [master, develop]

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name (merge)
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Publish to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile-mangosd
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/spp-mangosd-${{ env.BRANCH_NAME }}-amd64:latest
